# 数据抓取配置
crawler:
  # 数据抓取配置
  max_retries: 3
  timeout: 30
  batch_size: 10
  batch_interval: 1  # 秒
  
  # 调试配置
  debug_mode: true  # 调试模式，优先使用缓存数据
  force_refresh: true  # 强制刷新，忽略缓存
  cache_dir: "output/cache"  # 缓存目录
  request_delay: 2.0  # 请求间隔时间（秒）
  
  # 代理设置
  proxy: null

# 平台配置
platforms:
  # 新的API接口平台
  - id: "api_weibo"
    name: "微博热搜(API)"
    type: "weibo"
    url: "https://newsnow.busiyi.world/api/s?id=weibo"
    headers:
      accept: "*/*"
      accept-language: "zh-CN,zh;q=0.9"
      priority: "u=1, i"
      referer: "https://newsnow.busiyi.world/"
      sec-ch-ua: '"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"'
      sec-ch-ua-mobile: "?0"
      sec-ch-ua-platform: '"macOS"'
      sec-fetch-dest: "empty"
      sec-fetch-mode: "cors"
      sec-fetch-site: "same-origin"
      user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
      cookie: "_ga=GA1.1.1893853238.1760405052; _ga_EL9HHYE5LC=GS2.1.s1760419984$o3$g1$t1760419992$j52$l0$h0"
    enabled: true
    
  - id: "api_zhihu"
    name: "知乎热榜(API)"
    type: "zhihu"
    url: "https://newsnow.busiyi.world/api/s?id=zhihu"
    headers:
      accept: "*/*"
      accept-language: "zh-CN,zh;q=0.9"
      priority: "u=1, i"
      referer: "https://newsnow.busiyi.world/"
      sec-ch-ua: '"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"'
      sec-ch-ua-mobile: "?0"
      sec-ch-ua-platform: '"macOS"'
      sec-fetch-dest: "empty"
      sec-fetch-mode: "cors"
      sec-fetch-site: "same-origin"
      user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
      cookie: "_ga=GA1.1.1893853238.1760405052; _ga_EL9HHYE5LC=GS2.1.s1760419984$o3$g1$t1760419992$j52$l0$h0"
    enabled: true
    
  - id: "api_coolapk"
    name: "酷安热榜(API)"
    type: "news"
    url: "https://newsnow.busiyi.world/api/s?id=coolapk"
    headers:
      accept: "*/*"
      accept-language: "zh-CN,zh;q=0.9"
      priority: "u=1, i"
      referer: "https://newsnow.busiyi.world/"
      sec-ch-ua: '"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"'
      sec-ch-ua-mobile: "?0"
      sec-ch-ua-platform: '"macOS"'
      sec-fetch-dest: "empty"
      sec-fetch-mode: "cors"
      sec-fetch-site: "same-origin"
      user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
      cookie: "_ga=GA1.1.1893853238.1760405052; _ga_EL9HHYE5LC=GS2.1.s1760419984$o3$g1$t1760419992$j52$l0$h0"
    enabled: true

# 关键词配置
keywords:
  # 需要统计的关键词
  frequency_words:
    - "AI"
    - "人工智能"
    - "机器学习"
    - "深度学习"
    - "区块链"
    - "元宇宙"
    - "Web3"
    - "NFT"
    - "加密货币"
    - "比特币"
    - "以太坊"
    - "DeFi"
    - "新能源"
    - "电动车"
    - "自动驾驶"
    - "5G"
    - "6G"
    - "量子计算"
    - "云计算"
    - "大数据"
    
  # 词组匹配
  word_groups:
    - ["人工智能", "AI"]
    - ["机器学习", "深度学习"]
    - ["区块链", "blockchain"]
    - ["比特币", "BTC"]
    - ["以太坊", "ETH"]
    
  # 过滤词
  filter_words:
    - "广告"
    - "推广"
    - "营销"
    - "spam"
    
  # 排名阈值
  rank_threshold: 50

# 通知配置
notifications:
  # 飞书通知
  feishu:
    enabled: false
    webhook_url: ""
    secret: ""
    batch_size: 10
    batch_interval: 1
    
  # 钉钉通知
  dingtalk:
    enabled: false
    webhook_url: ""
    secret: ""
    batch_size: 10
    batch_interval: 1
    
  # 企业微信通知
  wework:
    enabled: false
    corp_id: ""
    corp_secret: ""
    agent_id: 0
    batch_size: 5
    
  # 邮件通知
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    from_email: ""
    to_emails: []
    use_tls: true
    batch_size: 5

# 报告配置
report:
  # HTML 报告
  html:
    enabled: true
    template_dir: "src/templates/html"
    output_dir: "output/html"
    filename: "trend_report_{{ timestamp }}.html"
    
  # 文本报告
  text:
    enabled: true
    template_dir: "src/templates/text"
    output_dir: "output/text"
    filename: "trend_report_{{ timestamp }}.md"

# 运行模式
mode:
  # 增量模式：只处理新数据
  incremental: true
  
  # 当前模式：处理当前数据
  current: false
  
  # 每日模式：每日定时运行
  daily: false

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "output/logs/trendradar.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# 版本信息
version: "2.0.0"